In [19]:
print("Welcome to our Patient Clustering Module")

Welcome to our Patient Clustering Module

In [20]:
# ==============================
# 1. IMPORT NECESSARY LIBRARIES
# ==============================

# For numerical operations
import numpy as np

# For data handling
import pandas as pd

# For splitting dataset
from sklearn.model_selection import train_test_split

# For feature scaling
from sklearn.preprocessing import StandardScaler

# For encoding categorical target
from sklearn.preprocessing import LabelEncoder

# Logistic Regression model
from sklearn.linear_model import LogisticRegression

# For model evaluation
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [21]:
# ==============================
# 2. LOAD THE DATASET
# ==============================

# Read CSV file
df = pd.read_csv("patient_priority.csv")

# Display first 5 rows
df.head()

,Unnamed: 0,age,gender,chest pain type,blood pressure,cholesterol,max heart rate,exercise angina,plasma glucose,skin_thickness,insulin,bmi,diabetes_pedigree,hypertension,heart_disease,Residence_type,smoking_status,triage
0,0,40.0,1.0,2.0,140.0,294.0,172.0,0.0,108.0,43.0,92.0,19.0,0.467386,0.0,0.0,Urban,never smoked,yellow
1,1,49.0,0.0,3.0,160.0,180.0,156.0,0.0,75.0,47.0,90.0,18.0,0.467386,0.0,0.0,Urban,never smoked,orange
2,2,37.0,1.0,2.0,130.0,294.0,156.0,0.0,98.0,53.0,102.0,23.0,0.467386,0.0,0.0,Urban,never smoked,yellow
3,3,48.0,0.0,4.0,138.0,214.0,156.0,1.0,72.0,51.0,118.0,18.0,0.467386,0.0,0.0,Urban,never smoked,orange
4,4,54.0,1.0,3.0,150.0,195.0,156.0,0.0,108.0,90.0,83.0,21.0,0.467386,0.0,0.0,Urban,never smoked,yellow

In [22]:
# ==============================
# 3. BASIC INFORMATION ABOUT DATA
# ==============================

# Check shape (rows, columns)
print("Shape of dataset:", df.shape)

# Check data types and null values
df.info()

# Check missing values (NULL values)
print("Missing Values:")
print(df.isnull().sum())

# Statistical summary of numerical columns
df.describe()

Shape of dataset: (6962, 18)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6962 entries, 0 to 6961
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         6962 non-null   int64
 1   age                6962 non-null   float64
 2   gender             6961 non-null   float64
 3   chest pain type    6962 non-null   float64
 4   blood pressure     6962 non-null   float64
 5   cholesterol        6962 non-null   float64
 6   max heart rate     6962 non-null   float64
 7   exercise angina    6962 non-null   float64
 8   plasma glucose     6962 non-null   float64
 9   skin_thickness     6962 non-null   float64
 10  insulin            6962 non-null   float64
 11  bmi                6962 non-null   float64
 12  diabetes_pedigree  6962 non-null   float64
 13  hypertension       6962 non-null   float64
 14  heart_disease      6962 non-null   float64
 15  Residence_type     6962 non-null   object
 16  smoking_status     6962 non-null   object
 17  triage             6552 non-null   object
dtypes: float64(14), int64(1), object(3)
memory usage: 979.2+ KB
Missing Values:
Unnamed: 0             0
age                    0
gender                 1
chest pain type        0
blood pressure         0
cholesterol            0
max heart rate         0
exercise angina        0
plasma glucose         0
skin_thickness         0
insulin                0
bmi                    0
diabetes_pedigree      0
hypertension           0
heart_disease          0
Residence_type         0
smoking_status         0
triage               410
dtype: int64

,Unnamed: 0,age,gender,chest pain type,blood pressure,cholesterol,max heart rate,exercise angina,plasma glucose,skin_thickness,insulin,bmi,diabetes_pedigree,hypertension,heart_disease
count,6962.000000,6962.000000,6961.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000,6962.000000
mean,2011.954180,57.450014,0.531964,0.529015,109.629991,184.711290,163.502442,0.061764,98.394283,56.813416,111.091640,27.190908,0.467386,0.071531,0.039500
std,1560.966466,11.904948,0.499013,1.253791,21.534852,32.010359,15.458693,0.240743,28.598084,22.889316,17.470033,7.362886,0.102663,0.257729,0.194796
min,0.000000,28.000000,0.000000,0.000000,60.000000,150.000000,138.000000,0.000000,55.120000,21.000000,81.000000,10.300000,0.078000,0.000000,0.000000
25%,604.000000,48.000000,0.000000,0.000000,92.000000,164.000000,150.000000,0.000000,78.707500,36.000000,97.000000,21.800000,0.467386,0.000000,0.000000
50%,1628.500000,56.000000,1.000000,0.000000,111.000000,179.000000,163.000000,0.000000,93.000000,55.000000,111.000000,26.200000,0.467386,0.000000,0.000000
75%,3368.750000,66.000000,1.000000,0.000000,127.000000,192.000000,177.000000,0.000000,111.632500,77.000000,125.000000,31.000000,0.467386,0.000000,0.000000
max,5109.000000,82.000000,1.000000,4.000000,165.000000,294.000000,202.000000,1.000000,199.000000,99.000000,171.000000,66.800000,2.420000,1.000000,1.000000

In [23]:
# ==============================
# 4. CHECK AND REMOVE DUPLICATES
# ==============================

# Check original shape
print("Original Shape:", df.shape)

# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Remove duplicates
df = df.drop_duplicates()

# Check shape after removing duplicates
print("Shape After Removing Duplicates:", df.shape)

Original Shape: (6962, 18)
Duplicate rows: 0
Shape After Removing Duplicates: (6962, 18)

In [24]:
#checking purpose
df['triage'].isnull().sum()

np.int64(410)

In [25]:
# ==============================
# 5. SET TARGET VARIABLE
# ==============================

# Target variable (what we want to predict)
y = df['triage']

In [26]:
# ==============================
# 6. SELECT IMPORTANT FEATURES
# ==============================

# Selecting important features from the dataset
X = df[['age',
        'blood pressure',
        'cholesterol',
        'max heart rate',
        'plasma glucose',
        'skin_thickness',
        'insulin',
        'bmi',
        'diabetes_pedigree']]

In [27]:
# ==============================
# 7. SPLIT INTO TRAIN AND TEST
# ==============================

# Splitting data into 80% training and 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [28]:
# ==============================
# 8. HANDLE CATEGORICAL TARGET
# ==============================

# Convert triage labels (yellow, orange, etc.) into numbers
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.transform(y_test)

In [29]:
# ==============================
# 9. FEATURE SCALING
# ==============================

# Scaling features for better model performance
scaler = StandardScaler()

# Fit on training data and transform
X_train = scaler.fit_transform(X_train)

# Only transform test data
X_test = scaler.transform(X_test)

In [30]:
# ==============================
# 10. TRAIN LOGISTIC REGRESSION
# ==============================

# Create Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Train the model using training data
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [31]:
# ==============================
# 11. MAKE PREDICTIONS
# ==============================

# Predict on test data
y_pred = model.predict(X_test)

In [32]:
# ==============================
# 12. MODEL EVALUATION
# ==============================

# Calculate accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

# Detailed performance report
print(classification_report(y_test, y_pred))

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Accuracy: 0.9138549892318737
              precision    recall  f1-score   support

           0       0.99      0.98      0.98        90
           1       0.58      0.55      0.57        58
           2       0.27      0.12      0.16        26
           3       0.95      0.97      0.96      1139
           4       0.63      0.60      0.62        80

    accuracy                           0.91      1393
   macro avg       0.68      0.64      0.66      1393
weighted avg       0.90      0.91      0.91      1393

Confusion Matrix:
[[  88    0    0    2    0]
 [   0   32    1   22    3]
 [   0    2    3    9   12]
 [   1   18    5 1102   13]
 [   0    3    2   27   48]]

In [33]:
# ==============================
# 13. SAMPLE PREDICTION
# ==============================

# Format:
# [age, chest pain type, blood pressure, cholesterol, max heart rate,
# exercise angina, plasma glucose, bmi, diabetes_pedigree]

sample_data = [[50, 3, 140, 220, 150, 0, 110, 25, 0.46]]

# Scale the sample data
sample_scaled = scaler.transform(sample_data)

# Predict triage level
prediction = model.predict(sample_scaled)

print("Predicted Triage Level:", prediction)

Predicted Triage Level: [4]

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(